// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtiyhggwpvhhbpvtttet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aXloZ2d3cHZoaGJwdnR0dGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDEyMDYsImV4cCI6MjA2OTIxNzIwNn0.8CGLev8RZPbz2tNM2H_lvvnmPtnK06kqmdZIfNm6SSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});